//设置权限
export const SET_PERMISSION='SET_PERMISSION';

//设置后台菜单TAB
export const SET_MENU_TAB_COMPONENTS='SET_MENU_TAB_COMPONENTS';

//显示后台路由加载进度条
export const SHOW_ROUTE_LOADING_LINE='SHOW_ROUTE_LOADING_LINE';

//隐藏后台路由加载进度条
export const HIDE_ROUTE_LOADING_LINE='HIDE_ROUTE_LOADING_LINE';

//设置路由加载进度条百分比
export const SET_ROUTE_LOADING_LINE_PERCENT='SET_ROUTE_LOADING_LINE_PERCENT';

//后台路由加载开始
export const SET_ROUTE_START='SET_ROUTE_START';

//后台路由加载完成
export const SET_ROUTE_COMPLETE='SET_ROUTE_COMPLETE';